# Generated by Django 5.1.1 on 2024-09-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('agent', 'Support Agent'), ('investigator', 'Investigator'), ('admin', 'Admin')], default='agent', max_length=12),
        ),
    ]
