# Generated by Django 5.1.1 on 2024-09-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_zone_alter_user_options_user_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('technician', 'Technician'), ('assistant', 'Engineering Assistant'), ('engineer', 'Engineer'), ('admin', 'Admin')], default='technician', max_length=50),
        ),
    ]
