# Generated by Django 5.1.1 on 2024-09-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['zone']},
        ),
    ]
