# Generated by Django 5.1.5 on 2025-02-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_zone_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('clerk', 'Clerk'), ('technician', 'Technician'), ('assistant', 'Engineering Assistant'), ('engineer', 'Engineer'), ('chief engineer', 'Chief Engineer'), ('chief engineer secretary', 'Chief Engineer Secretary'), ('deputy chief engineer', 'Deputy Chief Engineer'), ('deputy chief engineer secretary', 'Deputy Chief Engineer Secretary'), ('complaints officer', 'Complaints Officer')], default='technician', max_length=100),
        ),
    ]
