# Generated by Django 5.1.5 on 2025-02-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_role_user_is_chief_engineer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_chief_engineer',
            new_name='can_approve_works',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_complaints_officer',
            new_name='can_assign_eng',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_deputy_chief_engineer',
            new_name='can_assign_eng_asst',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_engineer',
            new_name='can_assign_tech',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_clerk',
            new_name='can_create_complaints',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_engineering_assistant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_technician',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
