# Generated by Django 5.1.5 on 2025-02-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_role_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_complaints_officer',
            field=models.BooleanField(default=False),
        ),
    ]
