# Generated by Django 5.1.5 on 2025-02-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_is_engineer_user_is_engineering_assistant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_register_users',
            field=models.BooleanField(default=False),
        ),
    ]
