# Generated by Django 5.1.1 on 2024-09-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaintphoto_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintphoto',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
