# Generated by Django 5.1.1 on 2024-09-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_category_name_alter_zone_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='slug',
            field=models.SlugField(blank=True, help_text='Your name', max_length=100, null=True, unique=True),
        ),
    ]
