# Generated by Django 5.1.1 on 2024-09-12 20:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
