# Generated by Django 5.1.1 on 2024-09-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='complaintinvestigator',
            options={'ordering': ['-created_at']},
        ),
    ]
