# Generated by Django 5.1.1 on 2024-09-17 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_alter_acknowledgementletter_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigninvestigator',
            name='investigator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigators', to=settings.AUTH_USER_MODEL),
        ),
    ]
