# Generated by Django 5.1.1 on 2024-09-17 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_alter_assigninvestigator_investigator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigninvestigator',
            name='investigator',
        ),
        migrations.AddField(
            model_name='assigninvestigator',
            name='investigator',
            field=models.ManyToManyField(related_name='investigators', to=settings.AUTH_USER_MODEL),
        ),
    ]
