# Generated by Django 5.1.1 on 2024-09-18 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_remove_assigninvestigator_investigator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigninvestigator',
            name='investigator',
        ),
        migrations.AddField(
            model_name='assigninvestigator',
            name='investigator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigators', to=settings.AUTH_USER_MODEL),
        ),
    ]
