# Generated by Django 5.1.1 on 2024-09-18 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_remove_assigninvestigator_investigator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigninvestigator',
            old_name='investigator',
            new_name='investigators',
        ),
    ]
