# Generated by Django 5.1.1 on 2024-09-18 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_changestatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changestatus',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Change Statuses'},
        ),
        migrations.AlterField(
            model_name='changestatus',
            name='status',
            field=models.CharField(choices=[('is_open', 'Open'), ('in_progress', 'In Progress'), ('is_resolved', 'Resolved'), ('is_closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='ChangePriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='low', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint')),
            ],
            options={
                'verbose_name_plural': 'Change Statuses',
                'ordering': ['-created_at'],
            },
        ),
    ]
