# Generated by Django 5.1.1 on 2024-09-18 11:44

import complaints.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0013_alter_changestatus_options_alter_changestatus_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='ref',
            field=models.CharField(default=complaints.utils.generate_short_id, editable=False, max_length=10, unique=True),
        ),
    ]
