# Generated by Django 5.1.1 on 2024-09-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0014_alter_complaint_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='district',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
