# Generated by Django 5.1.1 on 2024-09-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0015_alter_zone_district_alter_zone_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
