# Generated by Django 5.1.1 on 2024-09-18 15:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0017_alter_complaint_zone_delete_zone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssignInvestigator',
            new_name='AssignEngineer',
        ),
    ]
