# Generated by Django 5.1.1 on 2024-09-18 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0018_rename_assigninvestigator_assignengineer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignengineer',
            name='investigators',
        ),
        migrations.AddField(
            model_name='assignengineer',
            name='engineer',
            field=models.ManyToManyField(related_name='engineers', to=settings.AUTH_USER_MODEL),
        ),
    ]
