# Generated by Django 5.1.1 on 2024-09-18 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0019_remove_assignengineer_investigators_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignengineer',
            name='engineer',
        ),
        migrations.AddField(
            model_name='assignengineer',
            name='engineer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineers', to=settings.AUTH_USER_MODEL),
        ),
    ]
