# Generated by Django 5.1.1 on 2024-09-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0020_remove_assignengineer_engineer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignengineer',
            name='comment',
        ),
    ]
