# Generated by Django 5.1.1 on 2024-09-18 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0022_assigntechnician'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changepriority',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'change priorities'},
        ),
        migrations.AlterModelOptions(
            name='changestatus',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'change statuses'},
        ),
    ]
