# Generated by Django 5.1.1 on 2024-09-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0024_complaintcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint',
            field=models.TextField(null=True),
        ),
    ]
