# Generated by Django 5.1.1 on 2024-09-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0026_alter_complaint_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
