# Generated by Django 5.1.5 on 2025-02-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0029_assignengineeringassistant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='lat_location',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='long_location',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
    ]
