# Generated by Django 5.1.1 on 2024-09-18 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0023_alter_changepriority_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('report_description', models.TextField()),
                ('report_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=6)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='EngineerReportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='engineer_report_documents/')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.engineerreport')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('report_description', models.TextField()),
                ('report_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=6)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalReportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='technical_report_documents/')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.technicalreport')),
            ],
        ),
    ]
