# Generated by Django 5.1.1 on 2024-09-18 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_engineerreport_report_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='engineerreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engineer_report_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engineerreportdocument',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engineer_documents_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicalreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='technicalreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_report_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicalreportdocument',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_documents_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
