# Generated by Django 5.1.1 on 2024-09-18 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0023_alter_changepriority_options_and_more'),
        ('reports', '0003_engineerreport_created_at_engineerreport_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerreportdocument',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.complaint'),
        ),
        migrations.RemoveField(
            model_name='technicalreport',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='technicalreport',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='technicalreportdocument',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='engineerreportdocument',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportdocument',
            name='report_status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6),
        ),
        migrations.AddField(
            model_name='technicalreportdocument',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicalreportdocument',
            name='report_status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6),
        ),
        migrations.DeleteModel(
            name='EngineerReport',
        ),
        migrations.DeleteModel(
            name='TechnicalReport',
        ),
    ]
