# Generated by Django 5.1.1 on 2024-09-18 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0023_alter_changepriority_options_and_more'),
        ('reports', '0005_alter_technicalreportdocument_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineerreportdocument',
            old_name='report',
            new_name='complaint',
        ),
        migrations.RemoveField(
            model_name='technicalreportdocument',
            name='report',
        ),
        migrations.AddField(
            model_name='technicalreportdocument',
            name='complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='complaints.complaint'),
        ),
    ]
