# Generated by Django 5.1.1 on 2024-09-18 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0023_alter_changepriority_options_and_more'),
        ('reports', '0006_rename_report_engineerreportdocument_complaint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalreportdocument',
            name='complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_documents', to='complaints.complaint'),
        ),
    ]
