# Generated by Django 5.1.1 on 2024-09-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_technicalreportdocument_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineerreportdocument',
            name='report_status',
        ),
        migrations.RemoveField(
            model_name='technicalreportdocument',
            name='report_status',
        ),
    ]
