# Generated by Django 5.1.1 on 2024-09-20 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0023_alter_changepriority_options_and_more'),
        ('reports', '0008_remove_engineerreportdocument_report_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerreportdocument',
            name='complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineering_documents', to='complaints.complaint'),
        ),
    ]
