# Generated by Django 5.1.1 on 2024-09-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_engineerreportdocument_report_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaintreview',
            options={'ordering': ['-created_at']},
        ),
    ]
