# Generated by Django 5.1.1 on 2024-09-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_alter_complaintreview_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintreview',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='complaintreview',
            name='review',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('not-approved', 'Not Approved'), ('approved', 'Approved')], default='pending', max_length=12),
        ),
    ]
