# Generated by Django 5.1.1 on 2024-09-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_remove_complaintreview_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintreview',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
