# Generated by Django 5.1.1 on 2024-09-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_program_complaintreview_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintreview',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
