# Generated by Django 5.1.1 on 2024-09-25 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_complaintreview_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program',
            new_name='Programme',
        ),
        migrations.RemoveField(
            model_name='complaintreview',
            name='program',
        ),
        migrations.AddField(
            model_name='complaintreview',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.programme'),
        ),
    ]
