# Generated by Django 5.1.5 on 2025-02-07 14:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0030_delete_category_alter_complaint_lat_location_and_more'),
        ('reports', '0017_rename_program_programme_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringAssistantReportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='engineering_assistant_report_documents/')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('complaint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineering_assistant_documents', to='complaints.complaint')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engineer_assistant_documents_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
